### ISSUE TITLE
Customer's Orders should be a readonly collection

### ISSUE THREAD

**Issue by mizrael** [falberthen/EcommerceDDD#1]
the Orders collection on the Customer class should not allow adding new elements:
https://github.com/falberthen/EcommerceDDD/blob/master/EcommerceDDD.Domain/Customers/Customer.cs#L17
consider transforming to something like IReadonlyList or similar.

**Comment by falberthen** [comment]
> the Orders collection on the Customer class should not allow adding new elements:
> https://github.com/falberthen/EcommerceDDD/blob/master/EcommerceDDD.Domain/Customers/Customer.cs#L17
> consider transforming to something like IReadonlyList or similar.

thank you for pointing it! Fixed ;)
