### ISSUE TITLE
Value object constructor should be private

### ISSUE THREAD

**Issue by malballah** [falberthen/EcommerceDDD#17]
Hi @falberthen 
I am wondering if the value object and domains constructor should be private so no one can create an object with empty Guid

**Comment by falberthen** [comment]
Hello @malballah. This is how I implemented the domain objects. They have private constructors, while they count on a public static **CreateNew** method as their factory. AggregateRoot ones have it public, and Aggregates (child) have it internal to avoid they're being instantiated outside of the root. Regarding ValueObjects, I have just a few for now (with private constructors) and they don't have a GUID key. Is there a specific domain model I missed you can point out? 

Thanks for your contribution.

**Comment by malballah** [comment]
Hi @falberthen 
this is how the value object of order id looks like

![image](https://user-images.githubusercontent.com/6220899/148117372-9fe94a59-2fab-46bd-ba08-c5b8fce35d7b.png)

it has a public constructor which might allow someone to create an object from it with empty Guid I am asking if you have a point to make this public

**Comment by falberthen** [comment]
Oh got it. you're right, the IDs are VOs and you pointed it well. I was looking at all domain objects / VOs but the strong typed IDs =p

Gonna make a change to prevent what you pointed. Again, thank you for that.

**Comment by falberthen** [comment]
> Hi @falberthen this is how the value object of order id looks like
> 
> ![image](https://user-images.githubusercontent.com/6220899/148117372-9fe94a59-2fab-46bd-ba08-c5b8fce35d7b.png)
> 
> it has a public constructor which might allow someone to create an object from it with empty Guid I am asking if you have a point to make this public

I pushed a fix/validation for the base class. Kept the constructors public to not break the deserialization process from the MessagePublisher/Processor. Added some unit tests to assert the new behavior.
