### ISSUE TITLE
Building ECommerceDDD.IdentityServer Throws 'HostNotFound' Exception

### ISSUE THREAD

**Issue by stemadocafe** [falberthen/EcommerceDDD#25]
Hi Felipe,

This is more of a general FYI and it could have easily been an issue with my computer set-up, but I was unable to get the app to run after running `docker-compose up`.

I narrowed it down to when I would build ECommerceDDD.IdentityServer, the project would threw a 'HostNotFound' exception every time and then the app would not authenticate so the SPA was not responding. 

I found an alternative set-up for the IdentityServer and used the set-up supplied [here ](https://github.com/IdentityServer/IdentityServer4/issues/4592#issuecomment-651438287).

Using their set-up, I removed `DataSeeder.SeedConfiguration` and modified `builder.Services.AddIdentityServer` from

```
    builder.Services.AddIdentityServer(opt => 
            opt.IssuerUri = tokenIssuerSettings.GetValue<string>("Authority"))
        .AddDeveloperSigningCredential() // without a certificate, for dev only
        .AddAspNetIdentity<ApplicationUser>()
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = b => 
                b.UseNpgsql(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
        })
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = b => 
                b.UseNpgsql(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
            options.EnableTokenCleanup = true;
        });
```

to

```
builder.Services.AddIdentityServer(opt =>
        opt.IssuerUri = tokenIssuerSettings.GetValue<string>("Authority"))
    .AddDeveloperSigningCredential() // without a certificate, for dev only
    .AddInMemoryApiScopes(IdentityConfiguration.ApiScopes)
    .AddInMemoryApiResources(IdentityConfiguration.ApiResources)
    .AddInMemoryClients(IdentityConfiguration.Clients)
    .AddOperationalStore(options =>
    {
        options.ConfigureDbContext = b => b.UseNpgsql(connectionString);
        options.EnableTokenCleanup = true;
    })
    .AddConfigurationStore(options =>
    {
        options.ConfigureDbContext = b =>
            b.UseNpgsql(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
    })
    .AddAspNetIdentity<ApplicationUser>();
```

And with this I was able to build successfully and populate the database.

I'm not sure if this is an issue with something I did on my end or if this still produces the desired result, but after successfully building, I was able to use the app and it as able to authenticate.

Just wanted to drop this here in case it provides any value.

If not, feel free to delete (or let me know where I went wrong in my set-up.

Great work and great articles - they have been very helpful - primarily seeing your Angular SPA app at work with Event Sourcing.

Thanks!

**Comment by falberthen** [comment]
Hi @stemadocafe, you're right. This is a known issue, but I haven't had time to fix it. I thank you enormously for this fix and the support of my blog and projects. Would you mind making a pull request with the fix? I'd like to have you as a contributor. 

Regarding the solution, the only thing it wouldn't work is referring to the non-existing **IdentityConfiguration.ApiResources**. Did you add it as well? And as you said, the final solution should remove the DataSeeder class. 

Thank you so much

**Comment by stemadocafe** [comment]
@falberthen Good call! 

Yes, I did add `ApiResources` to the `IdentityConfiguration.cs`:

```
   // ApiScopes => (...)

    public static IEnumerable<ApiResource> ApiResources =>
        new ApiResource[]
        {
            new ApiResource(api_scope, "MyActions API")
            {
                Scopes = { api_scope }
            }
        };

   // Clients => (...)
```

Regarding the pull-request, you bet!

I will add the above ApiResources method `IdentityConfiguration.cs` in the pull request.

I will submit it first thing in the morning.
