### ISSUE TITLE
Identity increment int problem

### ISSUE THREAD

**Issue by malballah** [falberthen/EcommerceDDD#44]
I do not know how do we use it with the identity int incremental value that is only assigned to the entity when it saved to the database I see that you apply the event of creation once the domain model object is created as in Customer domain model
  private Customer(CustomerData customerData)
  {
      var @event = CustomerRegistered.Create(
          Guid.NewGuid(),
          customerData.Name,
          customerData.Email,
          customerData.ShippingAddress,
          customerData.CreditLimit);

      AppendEvent(@event);
      Apply(@event);
  }

what about creating a method in the aggregate root called Persisted and pass to it the generated Id value and may be called from the repository?

**Comment by falberthen** [comment]
> I do not know how do we use it with the identity int incremental value that is only assigned to the entity when it saved to the database I see that you apply the event of creation once the domain model object is created as in Customer domain model private Customer(CustomerData customerData) { var @event = CustomerRegistered.Create( Guid.NewGuid(), customerData.Name, customerData.Email, customerData.ShippingAddress, customerData.CreditLimit);
> 
> ```
>   AppendEvent(@event);
>   Apply(@event);
> ```
> 
> }
> 
> what about creating a method in the aggregate root called Persisted and pass to it the generated Id value and may be called from the repository?

Hi. The core idea of generating unique IDs for domain objects at the domain level was part of the design to ensure proper separation of concerns and keep the domain decoupled from persistence details or external infrastructure. Note that when using event sourcing and a non-relational approach for most of the services, so it's also convenient to keep it this way for implementation purposes.

**Comment by malballah** [comment]
.
